version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-image
    depends_on:
      - postgres
    env_file:
      - ./.env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./src:/src
    ports:
      - "8000:8000"

  postgres:
    build:
      context: .
      dockerfile: Dockerfile-db
    image: postgres:14
    env_file: 
      - ./.env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: