version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: api-image
    depends_on:
      - postgres
    env_file:
      - ./.env
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - DB_HOST=postgres
    volumes:
      - ./src:/src
    ports:
      - "8000:8000"

  postgres:
    build:
      context: .
      dockerfile: Dockerfile-db
    image: postgres:14
    env_file: 
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata: